all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      backend_url: localhost:4000
      jenkins_url: jenkins.localhost
      grafana_url: localhost
  children:
    servers:
      hosts:
        rpa1:
          ansible_host: 95.217.130.129
        rpa2:
          ansible_host: 95.217.130.126
      vars:
        ansible_port: 1337
        backend_url: backend.rpaboard.xyz
        jenkins_url: jenkins.rpaboard.xyz
        grafana_url: rpaboard.xyz
