all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
  children:
    servers:
      hosts:
        rpa1:
          ansible_host: 95.217.130.129
        rpa2:
          ansible_host: 95.217.130.126
      vars:
        ansible_port: 1337
