---
- hosts: all  
  gather_facts: no 
  vars_files:
    - vars.yml
  tasks:
  - name: Ensure cert-directory exists
    file:
      path: "{{ build_dir }}/certs"
      state: directory
  - name: Copy cert-script to server
    copy:
      src: certs/create_certs.sh
      dest: "{{ build_dir }}/certs/create_certs.sh"
  - name: Generate certificates
    shell: sh create_certs.sh 
    args:
      chdir: "{{ build_dir }}/certs"
      creates: "{{ build_dir }}/robo.crt"
  - name: Create jenkins api token file
    file: 
      path: "{{ build_dir }}/jenkins-api-token"
      state: touch
  - name: Create nginx configuration
    template:
      src: nginx.template
      dest: "{{ build_dir }}/nginx.conf"
      mode: '0400'
  - name: Create env-file
    template:
      src: .env
      dest: "{{ build_dir }}/.env"
      mode: '0400'
  - name: Copy docker-compose file to server
    copy:
      src: docker-compose.yml
      dest: "{{ build_dir }}/docker-compose.yml"