---
- hosts: all  
  gather_facts: no 
  vars_files:
    - vars.yml
  tasks:
  - name: Pull/Update repository
    git:
      repo: https://github.com/Robo-Project/rpa_dashboard.git
      dest: "{{ build_dir }}"
  - name: Generate certificates
    shell: sh create_certs.sh 
    args:
      chdir: "{{ build_dir }}/certs"
      creates: robo.crt
  - name: Create postgres.env 
    copy:
      src: postgres.vault
      dest: "{{ build_dir }}/postgres.env"
      mode: '0400'
  - name: Create jenkins api token file
    file: 
      path: "{{ build_dir }}/jenkins-api-token"
      state: touch
  - name: Create nginx configuration
    template:
      src: ./nginx.conf
      dest: "{{ build_dir }}/nginx.conf"
      mode: '0400'
    when: ansible_host != '127.0.0.1'
  - name: Create nginx configuration for localhost
    vars:
      jenkins_url: jenkins.localhost
      grafana_url: localhost
      backend_url: backend.localhost
    template:
      src: ./nginx.conf
      dest: "{{ build_dir }}/nginx.conf"
      mode: '0400'
    when: ansible_host == '127.0.0.1'
  - name: Create backend configuration
    template:
      src: ./backend.vault
      dest: "{{ build_dir }}/backend.env"
      mode: '0400'
    when: ansible_host != '127.0.0.1'
  - name: Create backend configuration for localhost
    vars:
      backend_url: https://backend.localhost
    template:
      src: ./backend.vault
      dest: "{{ build_dir }}/backend.env"
      mode: '0400'
    when: ansible_host == '127.0.0.1'
