---
- hosts: all  
  gather_facts: no 
  vars_files:
    - vars.yml
  tasks:
  - name: Ensure cert-directory exists
    file:
      path: "{{ build_dir }}/certs"
      state: directory
  - name: Copy cert-script to server
    copy:
      src: certs/create_certs.sh
      dest: "{{ build_dir }}/certs/create_certs.sh"
  - name: Generate certificates
    shell: sh create_certs.sh 
    args:
      chdir: "{{ build_dir }}/certs"
      creates: "{{ build_dir }}/robo.crt"
  - name: Create postgres.env 
    copy:
      src: postgres.vault
      dest: "{{ build_dir }}/postgres.env"
      mode: '0400'
  - name: Create jenkins api token file
    file: 
      path: "{{ build_dir }}/jenkins-api-token"
      state: touch
  - name: Create nginx configuration
    template:
      src: nginx.template
      dest: "{{ build_dir }}/nginx.conf"
      mode: '0400'
    when: ansible_host != '127.0.0.1'
  - name: Create nginx configuration for localhost
    vars:
      jenkins_url: jenkins.localhost
      grafana_url: localhost
      backend_url: backend.localhost
    template:
      src: nginx.template
      dest: "{{ build_dir }}/nginx.conf"
      mode: '0400'
    when: ansible_host == '127.0.0.1'
  - name: Create backend configuration
    template:
      src: backend.vault
      dest: "{{ build_dir }}/backend.env"
      mode: '0400'
    when: ansible_host != '127.0.0.1'
  - name: Create backend configuration for localhost
    vars:
      backend_url: https://backend.localhost
    template:
      src: backend.vault
      dest: "{{ build_dir }}/backend.env"
      mode: '0400'
    when: ansible_host == '127.0.0.1'
  - name: Copy docker-compose file to server
    copy:
      src: docker-compose.yml
      dest: "{{ build_dir }}/docker-compose.yml"