{
 "title": "RPA Board",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Successful jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  CASE WHEN status = 'PASS' THEN 1 ELSE 0 END AS \"now\",\n  name AS \"name\",\n  EXTRACT(epoch FROM finished_at) AS \"time\"\nFROM test_status\n  JOIN tests ON tests.id=test_status.test_id\n  JOIN test_runs ON test_runs.id=test_status.test_run_id\n  \n"
    }
   ]
  },
  {
   "title": "Elapsed time of jobs",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  started_at AS \"time\",\n  elapsed\nFROM test_run_status\n  JOIN test_runs ON test_runs.id=test_run_status.test_run_id \n  "
    }
   ]
  },
  {
   "title": "Job count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM test_status\n"
    }
   ]
  },
  {
   "title": "Average time /task run",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(elapsed) AS \"elapsed\"\nFROM test_run_status\n"
    }
   ]
  },
  {
   "title": "Success /failed",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(name)\nFROM tests\n  JOIN test_status ON tests.id=test_status.test_id\nWHERE\n  CASE WHEN status = 'PASS' THEN 1 ELSE 0 END = 1"
    },
    {
     "rawSql": "SELECT\n  count(name) AS \"succ\"\nFROM tests\n  JOIN test_status ON tests.id=test_status.test_id\nWHERE\n  CASE WHEN status = 'FAIL' THEN 1 ELSE 0 END = 1"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "content": "<form method=\"post\" action=\"http://localhost:8080/job/WikiSearch/job/master/build?SEARCH=Leonardo\" class=\"inline\" target=\"_blank\">\n  <button style=\"background: #222222;\n  cursor: pointer;\n  font-size: 1em;\n  font-family: serif;\" type=\"submit\" name=\"submit_param\" value=\"submit_value\" class=\"link-button\">\n    This is a link that sends a POST request\n  </button>\n</form>",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}